import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { AppState } from "@/lib/types";
import { generateDocxExport } from "@/lib/generateDocxExport";
import { Target, MessageCircle, BookOpen, BarChart3, Quote, Pencil, Download, FileText } from "lucide-react";

const PIP_LABELS = [
  { label: "Problem", badgeClasses: "bg-red-50 text-red-600 border border-red-200" },
  { label: "Inspiration", badgeClasses: "bg-amber-50 text-amber-600 border border-amber-200" },
  { label: "Payoff", badgeClasses: "bg-emerald-50 text-emerald-600 border border-emerald-200" },
];

interface Props {
  state: AppState;
  goToStep: (s: number) => void;
}

export function SummaryStep({ state, goToStep }: Props) {
  const shouldStatement = state.customShouldStatement || state.selectedShouldStatement;
  const [docxLoading, setDocxLoading] = useState(false);

  const handleDocxExport = async () => {
    setDocxLoading(true);
    try {
      await generateDocxExport(state);
    } finally {
      setDocxLoading(false);
    }
  };

  const handleExport = () => {
    let text = "STORY STUDIO — CONTENT TOOL\n";
    text += "=".repeat(40) + "\n\n";
    text += "BEHAVIOUR CHANGE:\n" + state.behaviourChange + "\n\n";
    text += "SHOULD STATEMENT:\n\"" + shouldStatement + "\"\n\n";
    text += "-".repeat(40) + "\n\n";
    const pipLabels = ["PROBLEM", "INSPIRATION", "PAYOFF"];
    state.selectedMessages.forEach((msg, i) => {
      text += "MESSAGE " + (i + 1) + " — " + (pipLabels[i] || "") + ": " + msg + "\n\n";
      text += "  Story: " + state.messages[i].story + "\n\n";
      text += "  Statistic: " + state.messages[i].statistic + "\n\n";
      text += "  Soundbite: \"" + state.messages[i].soundbite + "\"\n\n";
      text += "-".repeat(40) + "\n\n";
    });
    text += "\nGenerated by Story Studio Content Tool\nstorystudiocourse.com\n";
    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = "content-tool-plan.txt"; a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-5">
      <div>
        <h2 className="text-2xl font-semibold text-[#1F4E79] mb-1">Your Content Tool — Complete</h2>
        <p className="text-gray-500 text-sm mb-4">13 items that can convince anyone of anything.</p>
        <div className="flex gap-2 flex-wrap">
          <Button
            onClick={handleDocxExport}
            disabled={docxLoading}
            className="bg-[#1F4E79] hover:bg-[#163a5c] text-white gap-2"
          >
            <FileText className="w-4 h-4" />
            {docxLoading ? "Generating…" : "Download as Word"}
          </Button>
          <Button
            onClick={handleExport}
            variant="outline"
            className="border-[#2E75B6] text-[#2E75B6] hover:bg-[#EAF2FA] gap-2"
          >
            <Download className="w-4 h-4" /> Export as .txt
          </Button>
        </div>
      </div>

      <Card className="border-[#1F4E79] bg-[#1F4E79] text-white shadow-md">
        <CardContent className="pt-5 space-y-4">
          <div className="flex items-start gap-3">
            <Target className="w-5 h-5 mt-0.5 text-blue-300 flex-shrink-0" />
            <div>
              <p className="text-xs uppercase tracking-wider text-blue-300 mb-1">Behaviour Change</p>
              <p className="text-sm leading-relaxed">{state.behaviourChange}</p>
            </div>
          </div>
          <Separator className="bg-blue-400/30" />
          <div className="flex items-start gap-3">
            <MessageCircle className="w-5 h-5 mt-0.5 text-blue-300 flex-shrink-0" />
            <div>
              <p className="text-xs uppercase tracking-wider text-blue-300 mb-1">Should Statement</p>
              <p className="text-sm leading-relaxed italic">&ldquo;{shouldStatement}&rdquo;</p>
            </div>
          </div>
        </CardContent>
      </Card>

      {state.selectedMessages.map((msg, i) => (
        <Card key={i} className="border-gray-200 shadow-sm">
          <CardHeader className="pb-2">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <span className={`inline-flex items-center justify-center w-5 h-5 rounded-full text-[10px] font-bold flex-shrink-0 ${PIP_LABELS[i]?.badgeClasses}`}>
                  {i === 1 ? "I" : "P"}
                </span>
                <CardTitle className="text-base text-[#1F4E79]">
                  Message {i + 1} — {PIP_LABELS[i]?.label}
                </CardTitle>
              </div>
              <Button variant="ghost" size="sm" onClick={() => goToStep(3)}
                className="text-xs text-gray-400 hover:text-[#2E75B6]">
                <Pencil className="w-3 h-3 mr-1" /> Edit
              </Button>
            </div>
            <p className="text-sm text-gray-700 font-medium">{msg}</p>
          </CardHeader>
          <CardContent className="space-y-3">
            <div className="flex items-start gap-2.5 p-3 bg-gray-50 rounded">
              <BookOpen className="w-4 h-4 mt-0.5 text-[#2E75B6] flex-shrink-0" />
              <div>
                <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-0.5">Story</p>
                <p className="text-sm text-gray-700">{state.messages[i].story}</p>
              </div>
            </div>
            <div className="flex items-start gap-2.5 p-3 bg-gray-50 rounded">
              <BarChart3 className="w-4 h-4 mt-0.5 text-[#2E75B6] flex-shrink-0" />
              <div>
                <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-0.5">Statistic</p>
                <p className="text-sm text-gray-700">{state.messages[i].statistic}</p>
              </div>
            </div>
            <div className="flex items-start gap-2.5 p-3 bg-gray-50 rounded">
              <Quote className="w-4 h-4 mt-0.5 text-[#2E75B6] flex-shrink-0" />
              <div>
                <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-0.5">Soundbite</p>
                <p className="text-sm text-gray-700 italic">&ldquo;{state.messages[i].soundbite}&rdquo;</p>
              </div>
            </div>
          </CardContent>
        </Card>
      ))}

      <div className="text-center py-4 text-sm text-gray-400">
        Behaviour Change + Should Statement + 3 Messages × 3 Proofs = <strong className="text-[#1F4E79]">Your 13-Item Master Plan</strong>
      </div>
    </div>
  );
}
